[package]
name = "slicec-cs"
version = "0.3.0-preview1"
authors = ["ZeroC Inc."]
description = """
The slicec-cs compiler, for compiling Slice files into C# code.
"""
keywords = ["slice", "ice", "icerpc"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.70"

[dependencies]
clap = { version = "4.3.15", features = ["derive"] }
convert_case = "0.6.0"
in_definite = "1.0.0"
slicec = { git = "https://github.com/icerpc/slicec", rev = "299638df7656c8c0370d5fad9e7756978e2a88eb" }

[dev-dependencies]
test-case = "3.3.1"

[[bin]]
name = "slicec-cs"
path = "src/main.rs"
